-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.Pessoa
(
    cdpessoa serial,
    nome character varying(100) NOT NULL,
    fone character varying(30),
    PRIMARY KEY (cdpessoa)
);

CREATE TABLE IF NOT EXISTS public.Turma
(
    cdturma character varying(1),
    nome character varying(100),
    profe integer,
    PRIMARY KEY (cdturma)
);

CREATE TABLE IF NOT EXISTS public.Participante
(
    cdpessoa integer,
    cdturma character varying(1)
);

ALTER TABLE IF EXISTS public.Turma
    ADD FOREIGN KEY (profe)
    REFERENCES public.Pessoa (cdpessoa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.Participante
    ADD FOREIGN KEY (cdpessoa)
    REFERENCES public.Pessoa (cdpessoa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.Participante
    ADD FOREIGN KEY (cdturma)
    REFERENCES public.Turma (cdturma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
    
    

INSERT INTO public.Pessoa(nome, fone)	VALUES ('Obilac', '260088');
INSERT INTO public.Pessoa(nome, fone)	VALUES ('Silva', '282677');
INSERT INTO public.Pessoa(nome, fone)	VALUES ('Cabral', '260088');
INSERT INTO public.Pessoa(nome, fone)	VALUES ('Lobato', '174590');
INSERT INTO public.Pessoa(nome)	VALUES ('Mateus');

INSERT INTO public.Turma(cdturma, nome, profe) VALUES ('A', 'Volei', 4);
INSERT INTO public.Turma(cdturma, nome, profe) VALUES ('B', 'Karate', 4);
INSERT INTO public.Turma(cdturma, nome, profe) VALUES ('C', 'Natação', 2);

INSERT INTO public.Participante(cdpessoa, cdturma) VALUES (1, 'A');
INSERT INTO public.Participante(cdpessoa, cdturma) VALUES (3, 'A');
INSERT INTO public.Participante(cdpessoa, cdturma) VALUES (1, 'B');
INSERT INTO public.Participante(cdpessoa, cdturma) VALUES (1, 'C');
INSERT INTO public.Participante(cdpessoa, cdturma) VALUES (2, 'C');

END;


